"""
Palmer Penguins Data Loader

This module loads and processes structural size measurements and isotopic signatures
of foraging among adult male and female penguins nesting along the Palmer Archipelago
near Palmer Station, 2007-2009.

Data sources:
- Adelie penguins: knb-lter-pal.219.5
- Gentoo penguins: knb-lter-pal.220.7
- Chinstrap penguins: knb-lter-pal.221.8

Original code generated by the EDI Data Package Code Generator.
Refactored for modularity and reusability.
"""

import pandas as pd
from pathlib import Path


# Column names consistent across all datasets
COLUMN_NAMES = [
    "studyName",
    "Sample_Number",
    "Species",
    "Region",
    "Island",
    "Stage",
    "Individual_ID",
    "Clutch_Completion",
    "Date_Egg",
    "Culmen_Length",
    "Culmen_Depth",
    "Flipper_Length",
    "Body_Mass",
    "Sex",
    "Delta_15_N",
    "Delta_13_C",
    "Comments",
]

# NA values mapping (same for all columns)
NA_VALUES = {col: ['NULL'] for col in COLUMN_NAMES}

# Data URLs for each species
DATA_URLS = {
    'adelie': 'http://pasta.lternet.edu/package/data/eml/knb-lter-pal/219/5/002f3893385f710df69eeebe893144ff',
    'gentoo': 'http://pasta.lternet.edu/package/data/eml/knb-lter-pal/220/7/e03b43c924f226486f2f0ab6709d2381',
    'chinstrap': 'http://pasta.lternet.edu/package/data/eml/knb-lter-pal/221/8/fe853aa8f7a59aa84cdd3197619ef462',
}

# Package data directory for storing penguin CSV files
DATA_DIR = Path(__file__).parent / 'data' / 'penguins'


def _get_data_path(species: str) -> Path:
    """
    Get the data file path for a given species.
    
    Args:
        species: Name of the penguin species (e.g., 'adelie', 'gentoo', 'chinstrap')
        
    Returns:
        Path to the CSV file
    """
    return DATA_DIR / f'{species}_penguins.csv'


def _download_and_save(url: str, species: str) -> pd.DataFrame:
    """
    Download penguin data from URL and save it as package data.
    
    This function is used during package setup to download the data files.
    Normal users should not need to call this directly.
    
    Args:
        url: URL to the CSV data file
        species: Name of the species for filename
        
    Returns:
        DataFrame with raw data
    """
    # Download the data
    df = pd.read_csv(
        url,
        storage_options={'User-Agent': 'EDI_CodeGen'},
        skiprows=1,
        sep=",",
        quotechar='"',
        names=COLUMN_NAMES,
        parse_dates=['Date_Egg'],
        na_values=NA_VALUES
    )
    
    # Create data directory if it doesn't exist
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    
    # Save to package data directory
    data_path = _get_data_path(species)
    df.to_csv(data_path, index=False)
    print(f"Saved {species} penguin data to {data_path}")
    
    return df


def load_penguin_data(species: str = None, url: str = None, force_download: bool = False) -> pd.DataFrame:
    """
    Load penguin data from package data or download from URL.
    
    By default, loads from the CSV files included with the package. 
    Set force_download=True to download fresh data from the source URLs.
    
    Args:
        species: Name of the species ('adelie', 'gentoo', or 'chinstrap')
        url: URL to the CSV data file (optional, inferred from species if not provided)
        force_download: If True, download from URL instead of using package data
        
    Returns:
        DataFrame with properly typed columns
    """
    # Determine species name and URL
    if species is None and url is not None:
        # Try to infer species from URL
        for sp, sp_url in DATA_URLS.items():
            if sp_url == url:
                species = sp
                break
        if species is None:
            species = 'unknown'
    elif species is None:
        raise ValueError("Must provide either 'species' or 'url' parameter")
    
    # Set URL if not provided
    if url is None and species in DATA_URLS:
        url = DATA_URLS[species]
    
    # Check if package data file exists
    data_path = _get_data_path(species)
    
    if data_path.exists() and not force_download:
        # Load from package data
        df = pd.read_csv(
            data_path,
            parse_dates=['Date_Egg'],
            na_values=NA_VALUES
        )
    else:
        # Download from URL
        if url is None:
            raise ValueError(f"No URL available for species '{species}' and data file not found")
        df = _download_and_save(url, species)
    
    # Apply type coercion
    df = _coerce_types(df)
    
    return df


def _coerce_types(df: pd.DataFrame) -> pd.DataFrame:
    """
    Coerce DataFrame columns to appropriate types.
    
    Args:
        df: Raw DataFrame with data
        
    Returns:
        DataFrame with typed columns
    """
    # Categorical columns
    categorical_cols = [
        'studyName', 'Species', 'Region', 'Island', 'Stage',
        'Individual_ID', 'Clutch_Completion', 'Sex', 'Comments'
    ]
    for col in categorical_cols:
        df[col] = df[col].astype('category')
    
    # Numeric columns
    df['Sample_Number'] = pd.to_numeric(df['Sample_Number'], errors='coerce', downcast='integer')
    df['Culmen_Length'] = pd.to_numeric(df['Culmen_Length'], errors='coerce')
    df['Culmen_Depth'] = pd.to_numeric(df['Culmen_Depth'], errors='coerce')
    df['Flipper_Length'] = pd.to_numeric(df['Flipper_Length'], errors='coerce')
    df['Body_Mass'] = pd.to_numeric(df['Body_Mass'], errors='coerce')
    df['Delta_15_N'] = pd.to_numeric(df['Delta_15_N'], errors='coerce')
    df['Delta_13_C'] = pd.to_numeric(df['Delta_13_C'], errors='coerce')
    
    # Date column - add datetime version
    df = df.assign(Date_Egg_datetime=pd.to_datetime(df['Date_Egg'], errors='coerce'))
    
    return df


def print_data_summary(df: pd.DataFrame, species_name: str) -> None:
    """
    Print comprehensive summary statistics for a penguin dataset.
    
    Args:
        df: DataFrame containing penguin data
        species_name: Name of the penguin species for display
    """
    print(f"\n{'='*60}")
    print(f"Summary for {species_name.title()} Penguins")
    print(f"{'='*60}\n")
    
    print("DataFrame Info:")
    print(df.info())
    print("\n" + "-"*60 + "\n")
    
    print("Numerical Variables Summary:")
    print(df.describe())
    print("\n" + "-"*60 + "\n")
    
    print("Individual Variable Descriptions:")
    print("(Replace these basic descriptions with proper analyses after testing)\n")
    
    for col in COLUMN_NAMES:
        if col in df.columns:
            print(f"\n{col}:")
            print(df[col].describe())
            print("-"*30)


def load_all_species(force_download: bool = False) -> pd.DataFrame:
    """
    Load data for all three penguin species and merge into a single DataFrame.
    
    By default uses package data. Set force_download=True to download fresh data.
    
    Args:
        force_download: If True, download from URLs instead of using package data
    
    Returns:
        DataFrame containing all penguin species combined
    """
    adelie_df = load_penguin_data('adelie', force_download=force_download)
    gentoo_df = load_penguin_data('gentoo', force_download=force_download)
    chinstrap_df = load_penguin_data('chinstrap', force_download=force_download)
    
    # Merge all species into a single DataFrame
    merged_df = pd.concat([adelie_df, gentoo_df, chinstrap_df], ignore_index=True)
    
    return merged_df




# Print summaries if run as main script
if __name__ == '__main__':
    merged_df = load_all_species()
    print_data_summary(merged_df[merged_df['Species'] == 'Adelie'], 'adelie')
    print_data_summary(merged_df[merged_df['Species'] == 'Gentoo'], 'gentoo')
    print_data_summary(merged_df[merged_df['Species'] == 'Chinstrap'], 'chinstrap')
    print_data_summary(merged_df, 'all species combined')

                



