"""
Palmer Penguins Data Loader

This module loads and processes structural size measurements and isotopic signatures
of foraging among adult male and female penguins nesting along the Palmer Archipelago
near Palmer Station, 2007-2009.

Data sources:
- Adelie penguins: knb-lter-pal.219.5
- Gentoo penguins: knb-lter-pal.220.7
- Chinstrap penguins: knb-lter-pal.221.8

Original code generated by the EDI Data Package Code Generator.
Refactored for modularity and reusability.
"""

import pandas as pd


# Column names consistent across all datasets
COLUMN_NAMES = [
    "studyName",
    "Sample_Number",
    "Species",
    "Region",
    "Island",
    "Stage",
    "Individual_ID",
    "Clutch_Completion",
    "Date_Egg",
    "Culmen_Length",
    "Culmen_Depth",
    "Flipper_Length",
    "Body_Mass",
    "Sex",
    "Delta_15_N",
    "Delta_13_C",
    "Comments",
]

# NA values mapping (same for all columns)
NA_VALUES = {col: ['NULL'] for col in COLUMN_NAMES}

# Data URLs for each species
DATA_URLS = {
    'adelie': 'http://pasta.lternet.edu/package/data/eml/knb-lter-pal/219/5/002f3893385f710df69eeebe893144ff',
    'gentoo': 'http://pasta.lternet.edu/package/data/eml/knb-lter-pal/220/7/e03b43c924f226486f2f0ab6709d2381',
    'chinstrap': 'http://pasta.lternet.edu/package/data/eml/knb-lter-pal/221/8/fe853aa8f7a59aa84cdd3197619ef462',
} 



def load_penguin_data(url: str) -> pd.DataFrame:
    """
    Load penguin data from a URL and apply standard type coercion.
    
    Args:
        url: URL to the CSV data file
        
    Returns:
        DataFrame with properly typed columns
    """
    # Load the data
    df = pd.read_csv(
        url,
        storage_options={'User-Agent': 'EDI_CodeGen'},
        skiprows=1,
        sep=",",
        quotechar='"',
        names=COLUMN_NAMES,
        parse_dates=['Date_Egg'],
        na_values=NA_VALUES
    )
    
    # Apply type coercion
    df = _coerce_types(df)
    
    return df


def _coerce_types(df: pd.DataFrame) -> pd.DataFrame:
    """
    Coerce DataFrame columns to appropriate types.
    
    Args:
        df: Raw DataFrame with data
        
    Returns:
        DataFrame with typed columns
    """
    # Categorical columns
    categorical_cols = [
        'studyName', 'Species', 'Region', 'Island', 'Stage',
        'Individual_ID', 'Clutch_Completion', 'Sex', 'Comments'
    ]
    for col in categorical_cols:
        df[col] = df[col].astype('category')
    
    # Numeric columns
    df['Sample_Number'] = pd.to_numeric(df['Sample_Number'], errors='coerce', downcast='integer')
    df['Culmen_Length'] = pd.to_numeric(df['Culmen_Length'], errors='coerce')
    df['Culmen_Depth'] = pd.to_numeric(df['Culmen_Depth'], errors='coerce')
    df['Flipper_Length'] = pd.to_numeric(df['Flipper_Length'], errors='coerce')
    df['Body_Mass'] = pd.to_numeric(df['Body_Mass'], errors='coerce')
    df['Delta_15_N'] = pd.to_numeric(df['Delta_15_N'], errors='coerce')
    df['Delta_13_C'] = pd.to_numeric(df['Delta_13_C'], errors='coerce')
    
    # Date column - add datetime version
    df = df.assign(Date_Egg_datetime=pd.to_datetime(df['Date_Egg'], errors='coerce'))
    
    return df


def print_data_summary(df: pd.DataFrame, species_name: str) -> None:
    """
    Print comprehensive summary statistics for a penguin dataset.
    
    Args:
        df: DataFrame containing penguin data
        species_name: Name of the penguin species for display
    """
    print(f"\n{'='*60}")
    print(f"Summary for {species_name.title()} Penguins")
    print(f"{'='*60}\n")
    
    print("DataFrame Info:")
    print(df.info())
    print("\n" + "-"*60 + "\n")
    
    print("Numerical Variables Summary:")
    print(df.describe())
    print("\n" + "-"*60 + "\n")
    
    print("Individual Variable Descriptions:")
    print("(Replace these basic descriptions with proper analyses after testing)\n")
    
    for col in COLUMN_NAMES:
        if col in df.columns:
            print(f"\n{col}:")
            print(df[col].describe())
            print("-"*30)


def load_all_species() -> pd.DataFrame:
    """
    Load data for all three penguin species and merge into a single DataFrame.
    
    Returns:
        DataFrame containing all penguin species combined
    """
    adelie_df = load_penguin_data(DATA_URLS['adelie'])
    gentoo_df = load_penguin_data(DATA_URLS['gentoo'])
    chinstrap_df = load_penguin_data(DATA_URLS['chinstrap'])
    
    # Merge all species into a single DataFrame
    merged_df = pd.concat([adelie_df, gentoo_df, chinstrap_df], ignore_index=True)
    
    return merged_df




# Print summaries if run as main script
if __name__ == '__main__':
    merged_df = load_all_species()
    print_data_summary(merged_df[merged_df['Species'] == 'Adelie'], 'adelie')
    print_data_summary(merged_df[merged_df['Species'] == 'Gentoo'], 'gentoo')
    print_data_summary(merged_df[merged_df['Species'] == 'Chinstrap'], 'chinstrap')
    print_data_summary(merged_df, 'all species combined')

                



